# Server Configuration
server.port=8080
spring.application.name=java-service

# Actuator Telemetry & Prometheus Scraping Configuration
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always

# Disable Mongo Health indicator from Actuator to ensure that database connectivity failures
# do not bring the entire general service health report to 'DOWN'. This keeps the microservice operational.
management.health.mongo.enabled=false

# MongoDB Database Connection String
spring.data.mongodb.uri=${MONGO_URI:mongodb://admin:adminpassword@mongodb:27017/devopsdb?authSource=admin}
